[SERVICE]
  Flush         1
  Log_Level     info
  Parsers_File  /fluent-bit/etc/parsers.conf

[INPUT]
  Name    forward
  Listen  0.0.0.0
  Port    24224

[FILTER]
  Name          parser
  Match         *
  Key_Name      log
  Parser        docker
  Reserve_Data  True

[FILTER]
  Name    modify
  Match   *  
  Remove  log
  Remove  source

[FILTER]
  Name    grep
  Match   *
  Regex   msg .+

[OUTPUT]
  Name   stdout
  Match  *

[OUTPUT]
  Name         loki
  Match        go-boilerplateapi*
  Host         loki
  Port         3100
  Labels       service_name="go-boilerplateapi-api"
  line_format  json