basePath: /api
definitions:
  CreateCustomer:
    properties:
      first_name:
        example: John
        type: string
      last_name:
        example: Doe
        type: string
      phone:
        example: "00123456789"
        type: string
    required:
    - first_name
    - last_name
    - phone
    type: object
  Customer:
    properties:
      first_name:
        example: John
        type: string
      id:
        example: 1
        type: integer
      last_name:
        example: Doe
        type: string
      phone:
        example: "00123456789"
        type: string
    type: object
  ErrorResponse:
    properties:
      details:
        additionalProperties:
          type: string
        type: object
      message:
        type: string
    type: object
  PaginatedCustomer:
    properties:
      data:
        items:
          $ref: '#/definitions/Customer'
        type: array
      limit:
        type: integer
      page:
        type: integer
      total:
        type: integer
      total_pages:
        type: integer
    type: object
info:
  contact: {}
  description: API management for customers and services
  title: Ipanema Box API
  version: "1.0"
paths:
  /customers:
    get:
      consumes:
      - application/json
      description: Get a paginated list of customers
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Number of items per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/PaginatedCustomer'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: List customers
      tags:
      - customers
    post:
      consumes:
      - application/json
      description: Create a new customer
      parameters:
      - description: Customer input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/CreateCustomer'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/Customer'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Create a customer
      tags:
      - customers
swagger: "2.0"
